apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: deployapp
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-config
    namespace: flux-system
  validation: none
  path: ./apps/deployapp/${ENVIRONMENT}
  postBuild:
    substitute:
      NAMESPACE: "deployapp"
      CLUSTER_FULL_NAME: "${ENVIRONMENT}-${CLUSTER}"