apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/sbox/00
  postBuild:
    substitute:
      NAMESPACE: "podinfo"
      CLUSTER_FULL_NAME: "${ENVIRONMENT}-${CLUSTER}"
