---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxv2-basic
  validation: client
  path: ./clusters/${ENVIRONMENT}/${CLUSTER}